# resolution, caption_extension, batch_size, enable_bucket, bucket_no_upscale must be set in either general or datasets

# general configurations
[general]
resolution = [512, 512]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = false

[[datasets]]
video_directory = "./train/video_samples"
cache_directory = "./train/video_samples/cache"
target_frames = [1, 61]
frame_extraction = "head"
num_repeats = 4

# other datasets can be added here. each dataset can have different configurations