[wan_training]
task = "t2v-14B"
dataset_config_text = ""
dit_weights_path = "./models/ALL/Wan2_1-T2V-14B_fp8_e4m3fn.safetensors"
is_wan22 = false
dit_low_noise_path = ""
max_train_epochs = 12
learning_rate = "2e-4"
network_dim = 32
network_alpha = 16
blocks_to_swap = 0
fp8 = true
output_dir = "./output"
output_name = "xxx"
save_every_n_epochs = 2
use_network_weights = false
network_weights_path = "./output/xxx.safetensors"
attention_mode = "flash_attn"
mixed_precision = "bf16"
optimizer_type = "AdamW8bit"
gradient_accumulation_steps = 1
max_grad_norm = 1
lr_scheduler = "constant"
lr_warmup_steps = 0
timestep_sampling = "sigma"
discrete_flow_shift = 1
weighting_scheme = "cosmap"
enable_gradient_checkpointing = true
seed = 42
sample_every_n_epochs = 0
sample_prompts = "a woman walking --s 40 --w 640 --h 480 --f 16\na cat playing\na dog running in the park --s 40"
sample_steps = 15
sample_solver = "sa_ode_stable"
logging_dir = ""
wandb_run_name = ""
