# resolution, caption_extension, batch_size, enable_bucket, bucket_no_upscale must be set in either general or datasets

# general configurations
[general]
resolution = [512, 512]
caption_extension = ".txt"
batch_size = 4
enable_bucket = true
bucket_no_upscale = false

[[datasets]]
image_directory = "./train/image_samples"
cache_directory = "./train/image_samples/cache"
num_repeats = 4

# other datasets can be added here. each dataset can have different configurations